---
version: "3.7"
services:
  redshift:
    image: postgres:9.6
    cap_add:
      - IPC_LOCK
    privileged: true
    restart: always
    ports:
      - 5439:5432
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
  aws:
    image: motoserver/moto
    command: s3
  airflow:
    build: .
    restart: always
    entrypoint: /srv/bin/airflow_entrypoint
    depends_on:
      - redshift
      - aws
    volumes:
      - .:/srv
    ports:
      - 8080:8080
    environment:
      - AWS_ENDPOINT_URL=http://aws:5000
      - REDSHIFT_SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@redshift:5439/airflow
  ci:
    image: ${CACHE_IMAGE}
    build:
      context: .
      cache_from:
        - ${CACHE_IMAGE}
    command: /bin/bash
    stdin_open: true
  dev:
    build: .
    depends_on:
      - aws
    volumes:
      - .:/srv
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." -- pytest
    environment:
      - MOTO_SERVER_ENABLED=1
      - AWS_ENDPOINT_URL=http://aws:5000
